# -*- coding: utf-8 -*-
"""Ejercicio1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pZ4KxKwxPHnivbzt1e1IiufJNIUur32R

Instrucciones: Haga un programa en Python que reciba de parámetro un número de segundos y que despliegue en pantalla, las horas, minutos y segundos que representan.
"""

#Importamos MATH para poder utilizar la función FLOOR que nos servirá para redondear hacia abajo.
import math

#Se solicita el ingreso del número de segundos:
Tiempo = int(input("Ingrese el número de segundos: "))

#HORAS
#Se usa un condicional para saber si el número de segundo es mas de una hora, de lo contrario se muestra 0
if(Tiempo/3600)<1:
  horas = 0
else:
  horas = math.floor(Tiempo/3600) #Se redondea el número para no mostrar decimales, como el redondeo es hacia abajo se utiliza la función FLOOR

#MINUTOS
#Se usa un condicional para saber si el número de minutos es mas de uno, de lo contrario se muestra 0
if(Tiempo/60)<1:
  minutos = 0
else:
  minutos = math.floor((Tiempo%3600)/60)  #Se redondea el número para no mostrar decimales, como el redondeo es hacia abajo se utiliza la función FLOOR

#SEGUNDOS
#El residuo de la operación de minutos son los segundos

  segundos = (Tiempo%3600)%60  #Se redondea el número para no mostrar decimales

print("Horas: ", horas)
print("Minutos: ", minutos)
print("Segundos: ", segundos)