# -*- coding: utf-8 -*-
"""Ejercicio 5 V2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GbHCSc2eRFm4w5yHiIH2pI3wUKiMQ0dB
"""

try:
    #Se solicita que se ingrese el simbolo y las veces que se repetirá

    simbolo = input("Inserte un simbolo: ")
    repeticion = int(input("Inserte un número entre 1 y 20: "))

    #Se validan que los datos ingresados sean los correctos.
    if (repeticion <=0) or (repeticion > 20):  #Este valida que el número este entre 1 y 20
      raise ValueError('El número debe de ser entre 1 y 20.')
    if (len(simbolo) == 0): #Este valida que si se haya ingresado un caracter. 
      raise ValueError('Por favor ingrese un simbolo.')
    if ( len(simbolo) > 1):  #Este valida que solo se haya ingresado un caracter.
        raise ValueError('Debe de ingresar un solo caracter.')

    espacios = ' '*5  #Asigna los 5 espacios de separación. 

    #Ciclo For para hacer la figura. 

    for i in range(1, repeticion+1):  #El ciclo irá de 1 hasta donde se haya indicado. 
      valora=simbolo*i    #Multiplicará el simbolo por el ciclo actual del for. 
      valorb=simbolo*(repeticion-i+1)

      #Formato para cada una de las 4 figuras donde se intercalan una inversa a la otra.
      valor1="{0:<{vRepeticion}}".format(valora,vRepeticion=repeticion)
      valor2="{0:>{vRepeticion}}".format(valorb,vRepeticion=repeticion)
      valor3="{0:<{vRepeticion}}".format(valorb,vRepeticion=repeticion)
      valor4="{0:>{vRepeticion}}".format(valora,vRepeticion=repeticion)
      print(valor1+espacios+valor2+espacios+valor3+espacios+valor4) #Concatenado mostrado fila por fila hasta que finalice el for.

#Errores a mostrar en dado caso se de un error.
except ValueError as err:
  print('Datos Invalidos ',str(err.args[0]))
except Exception as ex:
  print('Hubo un problema: ', ex)