# -*- coding: utf-8 -*-
"""Ejercicio5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JEhDdFIdQAqf7UJrqo_7jqsRTNMEAT6w

Instrucciones: Haga un programa en Python que la fecha de nacimiento de una persona (puede ingresar
por separado cada valor, es decir pedir primero día, luego mes y luego año), despliegue
la edad de la persona en años, meses y días. Su resultado puede ser aproximado.
"""

import math  #Se importa la libreria math para poder usar la función Floor

#Se usa un Try para mostrar un error si ingresan números
try:

  #Se pide el ingreso del día, mes y año

  dia = int(input("Ingrese el día: "))
  mes = int(input("Ingrese el mes: "))
  anio = int(input("Ingrese el año: "))

  #Se dejan las variables a 0

  dias_vividos = 0
  dias_actuales = 0

  #Se usan 3 condicionales para asegurar que las fechas de día, mes y año sean correctos, sino se dice cual esta mal ingresado.

  if dia > 0 and dia < 31:
    if mes > 1 and mes < 13:
      if anio > 1899 and anio <= 2022:
          
          dias_vividos = anio*360 + mes*30 + dia #Calculo para tener los dias de vida
          dias_actuales = 2022*360 + 2*30 + 20 #Calculo para tener los días de vida para la fecha en que se entrego el problema

          tiempo_vida = dias_actuales - dias_vividos #Calculo los días de vida que es la diferencia entre las dos fechas anteriores

          #Con los siguientes calculos se obtiene los años, mes y días de vida:

          if(tiempo_vida/360)<1:
            anios_vida = 0
          else:
            anios_vida = math.floor(tiempo_vida/360) #Se redondea el número para no mostrar decimales, como el redondeo es hacia abajo se utiliza la función FLOOR

          #Meses
          #Se usa un condicional para saber si el número de meses es mas de uno, de lo contrario se muestra 0
          if(tiempo_vida/30)<1:
            meses_vida = 0
          else:
            meses_vida = math.floor((tiempo_vida%360)/30)  #Se redondea el número para no mostrar decimales, como el redondeo es hacia abajo se utiliza la función FLOOR

          #Días
          #El residuo de la operación de meses son los días

          dias_vida = (tiempo_vida%360)%30  #Se redondea el número para no mostrar decimales

          #Se muestra la respuesta:

          print("Su tiempo de vida es: ")
          print("Años: ", anios_vida)
          print("Meses: ", meses_vida)
          print("Días: ", dias_vida)

      #Los siguientes else son para mostrar que datos estan mal ingresados            
      else:
          print("Año Incorrecto")
    else:
          print("Mes Incorrecto")
  else:
          print("Día Incorrecto")

#Mensaje de error indicando que no se ingresaron números
except(ValueError):
    print("Error: debe ingresar números")